# Generated by Django 4.2.6 on 2023-10-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants_info',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
