# Generated by Django 4.2.6 on 2023-10-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants_info',
            name='is_deleted',
        ),
    ]
