# Generated by Django 4.2.6 on 2023-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0002_remove_plants_info_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants_info',
            name='water_frequency',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
