version: '3'

services:
  planty_be:
    container_name: planty_be
    build: .
    command: bash -c "python manage.py makemigrations Users && python manage.py makemigrations Plants && python manage.py makemigrations Devices && python manage.py makemigrations User_devices &&  python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    depends_on:
      - planty_db
      - redis
    ports:
      - "8080:8080"
    networks:
      - plantynet

  worker:
    container_name: planty_wr
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - planty_db
      - redis
    networks:
      - plantynet

  beat:
    container_name: planty_bt
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - planty_db
      - redis
    networks:
      - plantynet

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - plantynet

  planty_db:
    container_name: planty_db
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planty_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
    networks:
      - plantynet

volumes:
  pg_data:


networks:
  plantynet:
