# Generated by Django 4.2.6 on 2023-10-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_planty',
            name='image',
            field=models.ImageField(default='planty_default.webp', upload_to='planty_photos/'),
        ),
        migrations.AddField(
            model_name='users_planty',
            name='location',
            field=models.CharField(default='room'),
        ),
    ]
