# Generated by Django 4.2.6 on 2023-10-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_devices', '0002_users_planty_image_users_planty_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_planty',
            name='image',
        ),
        migrations.AddField(
            model_name='users_planty',
            name='image_url',
            field=models.URLField(default='gs://planty-app-htbn.appspot.com/planty_default.webp'),
        ),
    ]
