# Generated by Django 4.2.6 on 2023-10-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_devices', '0004_alter_users_planty_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_planty',
            name='image_url',
            field=models.URLField(blank=True, default='gs://planty-app-htbn.appspot.com/planty_default.webp', null=True),
        ),
    ]
