# Generated by Django 4.2.6 on 2023-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_devices', '0006_alter_users_planty_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_planty',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
