# Generated by Django 4.2.6 on 2023-10-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='is_deleted',
        ),
    ]
