# Generated by Django 4.2.7 on 2023-11-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userphoneevent_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='token',
            field=models.CharField(),
        ),
    ]
