# Generated by Django 4.2.7 on 2023-11-17 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_devices', '0001_initial'),
        ('Users', '0003_alter_userphone_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoneevent',
            name='user_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_devices.users_planty'),
        ),
    ]
