# Generated by Django 4.2.6 on 2023-11-04 15:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serie', models.CharField(unique=True)),
                ('timezone', models.IntegerField(blank=True, null=True)),
                ('actual_temperature', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('actual_light', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('actual_watering', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('plants_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Plants.plants_info')),
            ],
        ),
    ]
