# Generated by Django 4.2.6 on 2023-10-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planty',
            name='plants_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Plants.plants_info'),
        ),
    ]
